# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-19 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('push', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawldata',
            name='extra_data_1',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='crawldata',
            name='extra_data_2',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='crawldata',
            name='extra_data_3',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
